# Generated by Django 4.0.5 on 2022-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
