# Generated by Django 4.0.5 on 2022-06-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_alter_about_img_alter_banner_img_alter_slider_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='img',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
