# Generated by Django 4.0.5 on 2022-06-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_testimonial_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='section_title',
        ),
    ]
