# Generated by Django 4.0.5 on 2022-06-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_alter_testimonial_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='mini_description1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='mini_description2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='mini_title1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='mini_title2',
        ),
    ]
