# Generated by Django 4.0.5 on 2022-06-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_aboutdetails_remove_about_mini_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_testimonial_title', models.CharField(max_length=255)),
                ('section_banner_title', models.CharField(max_length=255)),
                ('section_about_title', models.CharField(max_length=255)),
                ('section_features_title', models.CharField(max_length=255)),
                ('section_team_title', models.CharField(max_length=255)),
                ('section_service_title', models.CharField(max_length=255)),
                ('section_started_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TestTitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='features',
            name='title',
        ),
    ]
