# Generated by Django 4.0.5 on 2022-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_site_info_delete_testtitle_remove_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_info',
            name='site_logo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
