# Generated by Django 4.0.5 on 2022-06-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_started_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
