# Generated by Django 4.0.5 on 2022-06-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_team_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('img', models.FileField(upload_to='')),
                ('fb_link', models.URLField()),
                ('Insta_link', models.URLField()),
                ('Linked_link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='Insta_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Linked_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='img',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='profession',
        ),
    ]
