# Generated by Django 4.0.5 on 2022-06-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_teammember_remove_team_insta_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='title',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
