# Generated by Django 4.0.5 on 2022-06-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_remove_newsletter_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='Email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
