# Generated by Django 4.0.5 on 2022-06-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0007_remove_newsletter_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RemoveField(
            model_name='started',
            name='title',
        ),
    ]
