# Generated by Django 4.0.5 on 2022-06-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='Insta_link',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='Linked_link',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='fb_link',
        ),
        migrations.CreateModel(
            name='Social_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.teammember')),
            ],
        ),
    ]
