# Generated by Django 4.0.5 on 2022-06-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0012_rename_email_newsletter_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('comments', models.TextField(max_length=500)),
            ],
        ),
    ]
